---
- name: Prepara a instalação openshift para alta disponibilidade
  hosts: masters
  become: true 
  vars:
    type: masters
    vrrp_script: "/usr/bin/true"
    vrrp_virtual_router_id: 41
    ha_vrrp_auth_pass: "s9daof"
  roles:
    - keepalived